services:
  postgres:
    image: postgres:16-alpine
    container_name: ingestion_governance_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ingestion_demo
    ports:
      - "5432:5432"
    volumes:
      - ingestion_governance_pgdata:/var/lib/postgresql/data

volumes:
  ingestion_governance_pgdata:
